[program:microweber-worker-staging]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/staging/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --queue=default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/staging/storage/logs/worker.log
stopwaitsecs=3600
environment=HOME="/var/www",USER="www-data"

[program:microweber-worker-staging-high]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/staging/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --queue=high,default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/staging/storage/logs/worker-high.log
stopwaitsecs=3600
environment=HOME="/var/www",USER="www-data"

[group:microweber-workers-staging]
programs=microweber-worker-staging,microweber-worker-staging-high
