[program:microweber-horizon]
process_name=%(program_name)s
command=/usr/bin/php /var/www/microweber/artisan horizon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/microweber/storage/logs/horizon.log
stopwaitsecs=3600
environment=HOME="/var/www",USER="www-data"

[program:microweber-horizon-supervisor]
process_name=%(program_name)s
command=/usr/bin/php /var/www/microweber/artisan horizon:supervisor
autostart=false
autorestart=false
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/microweber/storage/logs/horizon-supervisor.log
environment=HOME="/var/www",USER="www-data"
