[program:microweber-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/microweber/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --queue=default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/microweber/storage/logs/worker.log
stopwaitsecs=3600
environment=HOME="/var/www",USER="www-data"

[program:microweber-worker-high]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/microweber/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --queue=high,default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/microweber/storage/logs/worker-high.log
stopwaitsecs=3600
environment=HOME="/var/www",USER="www-data"

[program:microweber-worker-newsletter]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/microweber/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --queue=newsletter,default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/microweber/storage/logs/worker-newsletter.log
stopwaitsecs=3600
environment=HOME="/var/www",USER="www-data"

[program:microweber-worker-billing]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/microweber/artisan queue:work --sleep=3 --tries=5 --max-time=3600 --queue=billing,default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/microweber/storage/logs/worker-billing.log
stopwaitsecs=3600
environment=HOME="/var/www",USER="www-data"

[group:microweber-workers]
programs=microweber-worker,microweber-worker-high,microweber-worker-newsletter,microweber-worker-billing
