name: Check schedule
description: Check last commits

runs:
  using: "composite"
  steps:
    - name: Create cache file
    - run: |
        mkdir check-SHA
        echo ${{ github.sha }} > github-sha.txt

    - name: Check SHA
      id: check_sha
      uses: actions/cache@v1
      with:
        path: check-SHA
        key: check-SHA-${{ github.sha }}

    - name: Some subsequent steps
      if: steps.check_sha.outputs.cache-hit != 'true'
      run: |
      echo "Execute the subsequent steps"
      exit 1
