{{--
 type: layout
 name: Feature 43
 position: 43
 categories: Features
--}}

@php
    $classes['padding_top'] = $classes['padding_top'] ?? 'mw-p-t-80';
    $classes['padding_bottom'] = $classes['padding_bottom'] ?? '';
    $layout_classes = $layout_classes ?? ''; 
    $layout_classes .= ' ' . $classes['padding_top'] . ' ' . $classes['padding_bottom'] . ' ';
@endphp

<section class="section section-md py-5 {{ $layout_classes }} ">
    <module type="background" id="background-layout--{{ $params['id'] }}" />
    <module type="spacer" id="spacer-layout--{{ $params['id'] }}-top" />
    <div class="mw-layout-container no-element container edit" field="layout-feature-skin-43-{{ $params['id'] }}" rel="module">
        <div class="timeline mw-timeline safe-mode">
            <div class="mw-timeline-item cloneable element safe-mode">
                <i class="mw-micon-Data-Download" style="font-size: 40px;"></i>
                <div class="regular-mode">
                    <h5 data-mwplaceholder="{{ _e('Enter title here') }}" class="my-3">Create a Wallet</h5>
                    <p data-mwplaceholder="{{ _e('Enter text here') }}">Contact us and describe your problem. We are ready to help.</p>
                </div>
            </div>

            <div class="mw-timeline-item cloneable element safe-mode">
                <i class="mw-micon-Wallet" style="font-size: 40px;"></i>
                <div class="regular-mode">
                    <h5 data-mwplaceholder="{{ _e('Enter title here') }}" class="my-3">Save Your Seed Phrase</h5>
                    <p data-mwplaceholder="{{ _e('Enter text here') }}">A seed phrase is a series of words generated by your cryptocurrency wallet that give you access to the crypto associated with that wallet.</p>
                </div>
            </div>

            <div class="mw-timeline-item cloneable element safe-mode">
                <i class="mw-micon-Link" style="font-size: 40px;"></i>
                <div class="regular-mode">
                    <h5 data-mwplaceholder="{{ _e('Enter title here') }}" class="my-3">Connect Your Wallet</h5>
                    <p data-mwplaceholder="{{ _e('Enter text here') }}">Hundreds of dApp's use Wallet Connect to connect with wallets. Give users the choice to use your dApp with their favorite wallet on any device.</p>
                </div>
            </div>

            <div class="mw-timeline-item cloneable element safe-mode">
                <i class="mw-micon-Bitcoin" style="font-size: 40px;"></i>
                <div class="regular-mode">
                    <h5 data-mwplaceholder="{{ _e('Enter title here') }}" class="my-3">Buy Crypto</h5>
                    <p data-mwplaceholder="{{ _e('Enter text here') }}">The most popular venues to buy bitcoins are cryptocurrency exchanges, brokerages (crypto and mainstream), and payment services like Paypal.</p>
                </div>
            </div>
        </div>
    </div>
    <module type="spacer" id="spacer-layout--{{ $params['id'] }}-bottom" />
</section>
