{{--
 type: layout
 name: Feature 43
 position: 43
 categories: Features
--}}

<x-layout-section
    :params="$params"
    :classes="$classes"
    :layout-classes="$layout_classes ?? ''"
    section-class="section section-md py-5"
    field-name="layout-feature-skin-43"
    default-padding-top="mw-p-t-80"
    container-class="mw-layout-container no-element container edit"
>
    <div class="timeline mw-timeline safe-mode">
                <div class="mw-timeline-item cloneable element safe-mode">
                    <i class="mw-micon-Data-Download" style="font-size: 40px;"></i>
                    <div class="regular-mode">
                        <h5 data-mwplaceholder="{{ _e('Enter title here') }}" class="my-3">Create a Wallet</h5>
                        <p data-mwplaceholder="{{ _e('Enter text here') }}">Contact us and describe your problem. We are ready to help.</p>
                    </div>
                </div>

                <div class="mw-timeline-item cloneable element safe-mode">
                    <i class="mw-micon-Wallet" style="font-size: 40px;"></i>
                    <div class="regular-mode">
                        <h5 data-mwplaceholder="{{ _e('Enter title here') }}" class="my-3">Save Your Seed Phrase</h5>
                        <p data-mwplaceholder="{{ _e('Enter text here') }}">A seed phrase is a series of words generated by your cryptocurrency wallet that give you access to the crypto associated with that wallet.</p>
                    </div>
                </div>

                <div class="mw-timeline-item cloneable element safe-mode">
                    <i class="mw-micon-Link" style="font-size: 40px;"></i>
                    <div class="regular-mode">
                        <h5 data-mwplaceholder="{{ _e('Enter title here') }}" class="my-3">Connect Your Wallet</h5>
                        <p data-mwplaceholder="{{ _e('Enter text here') }}">Hundreds of dApp's use Wallet Connect to connect with wallets. Give users the choice to use your dApp with their favorite wallet on any device.</p>
                    </div>
                </div>

                <div class="mw-timeline-item cloneable element safe-mode">
                    <i class="mw-micon-Bitcoin" style="font-size: 40px;"></i>
                    <div class="regular-mode">
                        <h5 data-mwplaceholder="{{ _e('Enter title here') }}" class="my-3">Buy Crypto</h5>
                        <p data-mwplaceholder="{{ _e('Enter text here') }}">The most popular venues to buy bitcoins are cryptocurrency exchanges, brokerages (crypto and mainstream), and payment services like Paypal.</p>
                    </div>
                </div>
            </div>
</x-layout-section>
