/*{"mac":"1:a3c91019d6639a7eb161ed8eca1f1e09279441c99cd0b77aa1569900aa1c28e4","k":"0.15.0","version":"11129649","created":"2012-05-27T17:16:04Z"}*/
;(function(window,document,undefined){
var g=!0,j=null,k=!1;function l(a){return function(c){this[a]=c}}function m(a){return function(){return this[a]}}var n;function o(a,c,b){var e=2<arguments.length?Array.prototype.slice.call(arguments,2):[];return function(){e.push.apply(e,arguments);return c.apply(a,e)}}function p(a){this.q=a;this.T=void 0}n=p.prototype;
n.createElement=function(a,c,b){a=this.q.createElement(a);if(c)for(var e in c)if(c.hasOwnProperty(e))if("style"==e){var d=a,f=c[e];if(void 0===this.T){var h=this.q.createElement("p");h.innerHTML='<a style="top:1px;">w</a>';this.T=/top/.test(h.getElementsByTagName("a")[0].getAttribute("style"))}this.T?d.setAttribute("style",f):d.style.cssText=f}else a.setAttribute(e,c[e]);b&&a.appendChild(this.q.createTextNode(b));return a};
n.insertInto=function(a,c){var b=this.q.getElementsByTagName(a)[0];b||(b=document.documentElement);return b&&b.lastChild?(b.insertBefore(c,b.lastChild),g):k};n.whenBodyExists=function(a){function c(){document.body?a():setTimeout(c,0)}c()};n.removeElement=function(a){return a.parentNode?(a.parentNode.removeChild(a),g):k};n.createCssLink=function(a){return this.createElement("link",{rel:"stylesheet",href:a})};
n.appendClassName=function(a,c){for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return;b.push(c);a.className=b.join(" ").replace(/^\s+/,"")};n.removeClassName=function(a,c){for(var b=a.className.split(/\s+/),e=[],d=0,f=b.length;d<f;d++)b[d]!=c&&e.push(b[d]);a.className=e.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")};n.hasClassName=function(a,c){for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return g;return k};
function q(a,c,b,e,d,f,h){this.R=a;this.Oa=c;this.xa=b;this.wa=e;this.Ia=d;this.Ha=f;this.va=h}n=q.prototype;n.getName=m("R");n.getVersion=m("Oa");n.getEngine=m("xa");n.getEngineVersion=m("wa");n.getPlatform=m("Ia");n.getPlatformVersion=m("Ha");n.getDocumentMode=m("va");function s(a,c){this.j=a;this.u=c}var aa=new q("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",void 0);
s.prototype.parse=function(){var a;if(-1!=this.j.indexOf("MSIE"))if(a=t(this.j,/(MSIE [\d\w\.]+)/,1),""!=a){var c=a.split(" ");a=c[0];c=c[1];a=new q(a,c,a,c,u(this),v(this),w(this.u),6<=x(c))}else a=new q("MSIE","Unknown","MSIE","Unknown",u(this),v(this),w(this.u));else if(-1!=this.j.indexOf("Opera"))a:{var c=a="Unknown",b=t(this.j,/(Presto\/[\d\w\.]+)/,1);""!=b?(c=b.split("/"),a=c[0],c=c[1]):(-1!=this.j.indexOf("Gecko")&&(a="Gecko"),b=t(this.j,/rv:([^\)]+)/,1),""!=b&&(c=b));if(-1!=this.j.indexOf("Version/")&&
(b=t(this.j,/Version\/([\d\.]+)/,1),""!=b)){a=new q("Opera",b,a,c,u(this),v(this),w(this.u),10<=x(b));break a}b=t(this.j,/Opera[\/ ]([\d\.]+)/,1);a=""!=b?new q("Opera",b,a,c,u(this),v(this),w(this.u),10<=x(b)):new q("Opera","Unknown",a,c,u(this),v(this),w(this.u))}else if(-1!=this.j.indexOf("AppleWebKit")){a=u(this);c=v(this);b=t(this.j,/AppleWebKit\/([\d\.]+)/,1);""==b&&(b="Unknown");var e="Unknown";-1!=this.j.indexOf("Chrome")||-1!=this.j.indexOf("CrMo")?e="Chrome":-1!=this.j.indexOf("Safari")?
e="Safari":-1!=this.j.indexOf("AdobeAIR")&&(e="AdobeAIR");var d="Unknown";-1!=this.j.indexOf("Version/")?d=t(this.j,/Version\/([\d\.\w]+)/,1):"Chrome"==e?d=t(this.j,/(Chrome|CrMo)\/([\d\.]+)/,2):"AdobeAIR"==e&&(d=t(this.j,/AdobeAIR\/([\d\.]+)/,1));"AdobeAIR"==e?(t(d,/\d+\.(\d+)/,1),2<x(d)||x(d)):(t(b,/\d+\.(\d+)/,1),526<=x(b)||x(b));a=new q(e,d,"AppleWebKit",b,a,c,w(this.u))}else if(-1!=this.j.indexOf("Gecko")){c=a="Unknown";e=k;-1!=this.j.indexOf("Firefox")?(a="Firefox",b=t(this.j,/Firefox\/([\d\w\.]+)/,
1),""!=b&&(e=t(b,/\d+\.(\d+)/,1),c=b,e=""!=b&&3<=x(b)&&5<=parseInt(e,10))):-1!=this.j.indexOf("Mozilla")&&(a="Mozilla");b=t(this.j,/rv:([^\)]+)/,1);if(""==b)b="Unknown";else if(!e){var e=x(b),d=parseInt(t(b,/\d+\.(\d+)/,1),10),f=parseInt(t(b,/\d+\.\d+\.(\d+)/,1),10);1<e||1==e&&9<d||1==e&&9==d&&2<=f||b.match(/1\.9\.1b[123]/)!=j||b.match(/1\.9\.1\.[\d\.]+/)}a=new q(a,c,"Gecko",b,u(this),v(this),w(this.u))}else a=aa;return a};
function u(a){var c=t(a.j,/(iPod|iPad|iPhone|Android)/,1);if(""!=c)return c;a=t(a.j,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}function v(a){var c=t(a.j,/(OS X|Windows NT|Android|CrOS) ([^;)]+)/,2);if(c||(c=t(a.j,/(iPhone )?OS ([\d_]+)/,2)))return c;return(a=t(a.j,/Linux ([i\d]+)/,1))?a:"Unknown"}function x(a){a=t(a,/(\d+)/,1);return""!=a?parseInt(a,10):-1}function t(a,c,b){return(a=a.match(c))&&a[b]?a[b]:""}
function w(a){if(a.documentMode)return a.documentMode}function ba(a,c,b){this.c=a;this.l=c;this.V=b;this.o="wf";this.m=new y("-")}function A(a){a.c.removeClassName(a.l,a.m.k(a.o,"loading"));a.c.hasClassName(a.l,a.m.k(a.o,"active"))||a.c.appendClassName(a.l,a.m.k(a.o,"inactive"));C(a,"inactive")}function C(a,c,b,e){if(a.V[c])a.V[c](b,e)}function D(a,c,b,e,d){this.c=a;this.A=c;this.C=b;this.s=e;this.G=d;this.L=0;this.sa=this.ga=k}
D.prototype.watch=function(a,c,b,e,d){for(var f=a.length,h=0;h<f;h++){var i=a[h];c[i]||(c[i]=["n4"]);this.L+=c[i].length}d&&(this.ga=d);for(h=0;h<f;h++)for(var i=a[h],d=c[i],B=b[i],r=0,G=d.length;r<G;r++){var V=d[r],z=this.A,H=i,W=V;z.c.appendClassName(z.l,z.m.k(z.o,H,W,"loading"));C(z,"fontloading",H,W);z=o(this,this.ya);H=o(this,this.za);(new e(z,H,this.c,this.C,this.s,this.G,i,V,B)).start()}};
D.prototype.ya=function(a,c){var b=this.A;b.c.removeClassName(b.l,b.m.k(b.o,a,c,"loading"));b.c.removeClassName(b.l,b.m.k(b.o,a,c,"inactive"));b.c.appendClassName(b.l,b.m.k(b.o,a,c,"active"));C(b,"fontactive",a,c);this.sa=g;E(this)};D.prototype.za=function(a,c){var b=this.A;b.c.removeClassName(b.l,b.m.k(b.o,a,c,"loading"));b.c.hasClassName(b.l,b.m.k(b.o,a,c,"active"))||b.c.appendClassName(b.l,b.m.k(b.o,a,c,"inactive"));C(b,"fontinactive",a,c);E(this)};
function E(a){0==--a.L&&a.ga&&(a.sa?(a=a.A,a.c.removeClassName(a.l,a.m.k(a.o,"loading")),a.c.removeClassName(a.l,a.m.k(a.o,"inactive")),a.c.appendClassName(a.l,a.m.k(a.o,"active")),C(a,"active")):A(a.A))}
function F(a,c,b,e,d,f,h,i,B){this.ta=a;this.Ca=c;this.c=b;this.C=e;this.s=d;this.G=f;this.Ga=new I;this.Ba=new J;this.aa=h;this.$=i;this.Aa=B||"BESbswy";this.ia=K(this,"arial,'URW Gothic L',sans-serif");this.ja=K(this,"Georgia,'Century Schoolbook L',serif");this.ea=this.ia;this.fa=this.ja;this.na=L(this,"arial,'URW Gothic L',sans-serif");this.oa=L(this,"Georgia,'Century Schoolbook L',serif")}F.prototype.start=function(){this.Ma=this.G();this.W()};
F.prototype.W=function(){var a=this.C.O(this.na),c=this.C.O(this.oa);(this.ia!=a||this.ja!=c)&&this.ea==a&&this.fa==c?ca(this,this.ta):5E3<=this.G()-this.Ma?ca(this,this.Ca):(this.ea=a,this.fa=c,da(this))};function da(a){a.s(function(a,b){return function(){b.call(a)}}(a,a.W),25)}function ca(a,c){a.c.removeElement(a.na);a.c.removeElement(a.oa);c(a.aa,a.$)}function K(a,c){var b=L(a,c,g),e=a.C.O(b);a.c.removeElement(b);return e}
function L(a,c,b){c=a.c.createElement("span",{style:ea(a,c,a.$,b)},a.Aa);a.c.insertInto("body",c);return c}function ea(a,c,b,e){b=a.Ba.expand(b);return"position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;font-family:"+(e?"":a.Ga.quote(a.aa)+",")+c+";"+b}function y(a){this.Ea=a||"-"}y.prototype.k=function(a){for(var c=[],b=0;b<arguments.length;b++)c.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return c.join(this.Ea)};
function I(){this.ma="'"}I.prototype.quote=function(a){for(var c=[],a=a.split(/,\s*/),b=0;b<a.length;b++){var e=a[b].replace(/['"]/g,"");-1==e.indexOf(" ")?c.push(e):c.push(this.ma+e+this.ma)}return c.join(",")};function J(){this.ka=fa;this.D=ga}var fa=["font-style","font-weight"],ga={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function ha(a,c,b){this.Da=a;this.Ja=c;this.D=b}ha.prototype.expand=function(a,c){for(var b=0;b<this.D.length;b++)if(c==this.D[b][0]){a[this.Da]=this.Ja+":"+this.D[b][1];break}};J.prototype.expand=function(a){if(2!=a.length)return j;for(var c=[j,j],b=0,e=this.ka.length;b<e;b++){var d=this.ka[b];(new ha(b,d,this.D[d])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":j};function M(a,c){this.q=a;this.j=c}M.prototype=p.prototype;M.prototype.isHttps=function(){return"https:"==this.q.location.protocol};
M.prototype.getHostName=function(){return this.q.location.hostname};M.prototype.loadScript=function(a,c){var b=this.q.getElementsByTagName("head")[0];if(b){var e=this.q.createElement("script");e.src=a;var d=k;e.onload=e.onreadystatechange=function(){if(!d&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))d=g,c&&c(),e.onload=e.onreadystatechange=j,"HEAD"==e.parentNode.tagName&&b.removeChild(e)};b.appendChild(e)}};
M.prototype.createStyle=function(a){var c=this.q.createElement("style");c.setAttribute("type","text/css");c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a));return c};function ia(a,c){this.Ka=a;this.Y=c}function ja(a){for(var c=a.Ka.join(","),b=[],e=0;e<a.Y.length;e++){var d=a.Y[e];b.push(d.name+":"+d.value+";")}return c+"{"+b.join("")+"}"}function N(a,c,b){this.B=a;this.F=c;this.v=b;this.ba={};this.Z={}}
N.prototype.w=function(a){return a?(this.ba[a.getStylesheetFormatId()]||this.F).slice(0):this.F.slice(0)};N.prototype.getId=m("v");function ka(a,c,b){for(var e=[],d=a.B.split(",")[0].replace(/"|'/g,""),f=a.w(),h,i=[],B={},r=0;r<f.length;r++)h=f[r],0<h.length&&!B[h]&&(B[h]=g,i.push(h));b=b.la?b.la(d,i,e):i;c=c.getStylesheetFormatId();a.ba[c]=b;a.Z[c]=e}N.prototype.watch=function(a,c,b){var e=[],d={};la(this,c,e,d);a(e,d,b)};
function la(a,c,b,e){b.push(a.B);e[a.B]=a.w(c);a=a.Z[c.getStylesheetFormatId()]||[];for(c=0;c<a.length;c++){for(var d=a[c],f=d.B,h=k,i=0;i<b.length;i++)b[i]==f&&(h=g);h||(b.push(f),e[f]=d.w())}}function ma(a,c){this.B=a;this.F=c}ma.prototype.w=m("F");function O(a,c,b){this.La=a;this.P=c;this.pa=b}O.prototype.buildUrl=function(a,c){var b=this.La&&a?"https:":"http:",e="function"==typeof this.P?this.P(b):this.P;return b+"//"+e+("/"==this.pa?"":this.pa)+c};
function na(a){var c=new Image(1,1);c.src=a;c.onload=function(){c.onload=j}}function P(a,c,b){this.v=a;this.ra=c;this.da=b}P.prototype.getId=m("v");P.prototype.getStylesheetFormatId=m("ra");P.prototype.isUserAgent=function(a){return this.da?this.da(a.getName(),a.getVersion(),a.getEngine(),a.getEngineVersion(),a.getPlatform(),a.getPlatformVersion(),a.getDocumentMode()):k};P.prototype.buildCssUrl=function(a,c,b,e){b="/"+b+"-"+this.ra+".css";e&&(b+="?"+e);return c.buildUrl(a,b)};
function Q(){this.t=[]}Q.prototype.addBrowser=function(a){this.getBrowserById(a.getId())||this.t.push(a)};Q.prototype.getBrowserById=function(a){for(var c=0;c<this.t.length;c++){var b=this.t[c];if(a===b.getId())return b}return j};Q.prototype.findBrowser=function(a){for(var c=0;c<this.t.length;c++){var b=this.t[c];if(b.isUserAgent(a))return b}return j};Q.prototype.addBrowsersToBrowserSet=function(a){for(var c=0;c<this.t.length;c++)a.addBrowser(this.t[c])};
function oa(a){this.v=a;this.I=new Q;this.n=[];this.K=[];this.M=this.X=this.z=j}n=oa.prototype;n.getId=m("v");n.setSecurityToken=l("qa");n.setNestedUrl=l("ha");n.setFontFilterSet=l("M");n.setKitOptions=l("Q");n.addBrowser=function(a){this.I.addBrowser(a)};n.addFontFamily=function(a){this.n.push(a)};n.addCssRule=function(a){this.K.push(a)};n.supportsBrowser=function(a){return!!this.I.getBrowserById(a.getId())};n.addBrowsersToBrowserSet=function(a){this.I.addBrowsersToBrowserSet(a)};
n.init=function(a){for(var c=[],b=0;b<this.K.length;b++)c.push(ja(this.K[b]));a.insertInto("head",a.createStyle(c.join("")))};
n.load=function(a,c,b,e){if(this.M)for(var d=pa(this.M,b.getStylesheetFormatId()),f=0;f<this.n.length;f++)ka(this.n[f],b,d);if(this.z&&this.X){this.z.ua(new qa(b.getStylesheetFormatId()));f=new ra(a,b,this.n);d=sa(this.X,b.getStylesheetFormatId(),f);for(f=0;f<d.length;f++)this.z.ua(d[f]);this.z.Qa(this.qa);f=this.z.buildUrl(a.isHttps(),this.ha)}else f=b.buildCssUrl(a.isHttps(),this.ha,this.v,this.qa);a.insertInto("head",a.createCssLink(f));c&&a.whenBodyExists(function(a,b,c,d){return function(){for(var e=
0;e<a.n.length;e++)a.n[e].watch(b,c,d&&e==a.n.length-1)}}(this,c,b,e))};n.collectFontFamilies=function(a,c,b){for(var e=0;e<this.n.length;e++)la(this.n[e],a,c,b)};n.performOptionalActions=function(a,c,b){this.Q&&b.whenBodyExists(function(a,b,c,h){return function(){var b=a.Q;if(b.S){var d=b.S.Pa(window,h.getHostName());na(b.S.k(h.isHttps(),d))}d=a.Q;b=a.v;d.U&&(d=d.U.k(b,c,h),d.setAttribute("id","typekit-badge-"+b),h.insertInto("body",d))}}(this,a,c,b))};
function R(a,c,b,e,d){this.Fa=a;this.c=c;this.j=b;this.l=e;this.s=d;this.p=[]}R.prototype.H=function(a){this.p.push(a)};R.prototype.load=function(a,c){var b=a,e=c||{};if("string"==typeof b)b=[b];else if(!b||!b.length)e=b||{},b=[];if(b.length)for(var d=this,f=b.length,h=0;h<b.length;h++)ta(this,b[h],function(){0==--f&&ua(d,e)});else ua(this,e)};function ta(a,c,b){a.c.loadScript(a.Fa.buildUrl(a.c.isHttps(),"/"+c+".js"),b)}
function ua(a,c){c.userAgent&&(a.j=(new s(c.userAgent,document)).parse());for(var b=new ba(a.c,a.l,c),e=new Q,d=0;d<a.p.length;d++)a.p[d].addBrowsersToBrowserSet(e);e=e.findBrowser(a.j);for(d=0;d<a.p.length;d++)a.p[d].init(a.c);e?(b.c.appendClassName(b.l,b.m.k(b.o,"loading")),C(b,"loading"),va(a,e,b)):A(b);a.p=[]}
function va(a,c,b){function e(a,b,c){d.watch(a,b,{},F,c)}for(var d=new D(a.c,b,{O:function(a){return a.offsetWidth}},a.s,function(){return+new Date}),b=0;b<a.p.length;b++){var f=a.p[b];f.supportsBrowser(c)&&(f.load(a.c,e,c,b==a.p.length-1),f.performOptionalActions(window,a.j,a.c))}}function S(a,c,b){this.ca=a;this.c=c;this.s=b;this.p=[]}S.prototype.H=function(a){this.p.push(a)};
S.prototype.load=function(){var a=this.ca.__webfonttypekitmodule__;if(a)for(var c=0;c<this.p.length;c++){var b=this.p[c],e=a[b.getId()];if(e){var d=this.c,f=this.s;e(function(a,c,e){var r=new Q;b.addBrowsersToBrowserSet(r);var c=[],G={};if(r=r.findBrowser(a))b.init(d),b.load(d,j,r,f),b.collectFontFamilies(r,c,G),b.performOptionalActions(window,a,d,f);e(!!r,c,G)})}}};function T(a,c){this.R=a;this.la=c}T.prototype.getName=m("R");function wa(a){var c=U;xa(c,a.getName())||c.N.push(a)}
function xa(a,c){for(var b=0;b<a.N.length;b++){var e=a.N[b];if(c===e.getName())return e}return j}function pa(a,c){var b=a.r[c];return b?xa(a,b):j}function sa(a,c,b){for(var e=[],a=a.Ra[c]||[],c=0;c<a.length;c++){var d;a:switch(a[c]){case "observeddomain":d=new ya(b.c);break a;case "fontmask":d=new za(b.J,b.n);break a;default:d=j}d&&e.push(d)}return e}function ra(a,c,b){this.c=a;this.J=c;this.n=b}function qa(a){this.Na=a}qa.prototype.toString=m("Na");function ya(a){this.c=a}
ya.prototype.toString=function(){var a;a=this.c.getHostName?this.c.getHostName():document.location.hostname;return encodeURIComponent(a)};function za(a,c){this.J=a;this.n=c}
za.prototype.toString=function(){for(var a=[],c=0;c<this.n.length;c++)for(var b=this.n[c],e=b.w(),b=b.w(this.J),d=0;d<e.length;d++){var f;a:{for(f=0;f<b.length;f++)if(e[d]===b[f]){f=g;break a}f=k}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");c=[];for(e=a.length;0<e;e-=4)b=a.slice(0>e-4?0:e-4,e),c.unshift(parseInt(b,2).toString(16));return c.join("")};var X=new Q;
X.addBrowser(new P("ie6to8-win2003-win7plus-winvista-winxp","i",function(a,c,b,e,d,f,h){var i;i=k||("Windows"==d&&"5.1"==f?g:k)||("Windows"==d&&"5.2"==f?g:k)||("Windows"==d&&"6.0"==f?g:k)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):k}(a,c,b,e,d,f,h);return!i?k:function(a,b,c,d,e,f,h){if("MSIE"==a)return(a=/([0-9]+.[0-9]+)/.exec(b))?6<=parseFloat(a[1])&&(void 0===h||9>h):k}(a,c,b,e,d,f,h)}));
X.addBrowser(new P("safari3to5-osx","b",function(a,c,b,e,d,f,h){var i;i=k||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?g:k}(a,c,b,e,d,f,h);return!i?k:function(a,b,c,d){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(d))?(a=parseFloat(a[1]),525.13<=a&&534.5>a):k}(a,c,b,e,d,f,h)}));
X.addBrowser(new P("air-linux-win","a",function(a,c,b,e,d,f){if(k||("Windows"==d&&"Unknown"==f?g:k)||("Ubuntu"==d||"Linux"==d?g:k))a:{if("AdobeAIR"==a&&(a=/([0-9]+.[0-9]+)/.exec(c))){a=2.5<=parseFloat(a[1]);break a}a=k}else a=k;return a}));
X.addBrowser(new P("ff36plus-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,e,d,f,h){var i;i=(i=k||("Windows"==d&&"5.1"==f?g:k)||("Windows"==d&&"5.2"==f?g:k)||("Windows"==d&&"6.0"==f?g:k)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):k}(a,c,b,e,d,f,h))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==
e&&"Unknown"==f?g:k}(a,c,b,e,d,f,h);return!i&&!("Ubuntu"==d||"Linux"==d?g:k)?k:function(a,b,c,e){return"Gecko"==c&&(b=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(e))?(a=parseFloat(b[1]),b=parseInt(b[3],10),1.9<a||1.9<=a&&1<b):k}(a,c,b,e,d,f,h)}));
X.addBrowser(new P("safariany-android3plus","f",function(a,c,b,e,d,f){if(!(c=k))c=/([0-9]+).([0-9]+)/.exec(f),"Android"==d&&c?(f=parseInt(c[1],10),c=parseInt(c[2],10),c=3==f&&1<=c||3<f):c=k;return!c?k:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==d||"iPad"==d)?g:k}));
X.addBrowser(new P("ie9plus-win7plus-winvista","d",function(a,c,b,e,d,f,h){if(!(c=k))b=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&b?(c=parseInt(b[1],10),b=parseInt(b[2],10),c=6<c||6==c&&1<=b):c=k;a=c||("Windows"==d&&"6.0"==f?g:k)?"MSIE"==a?9<=h:void 0:k;return a}));
X.addBrowser(new P("opera10-osx","b",function(a,c,b,e,d,f,h){var i;i=k||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?g:k}(a,c,b,e,d,f,h);return!i?k:function(a,b){if("Opera"==a){var c=parseFloat(b);return 10.54<=c&&11.1>c}return k}(a,c,b,e,d,f,h)}));
X.addBrowser(new P("safari3to5-win2003-win7plus-winvista-winxp","a",function(a,c,b,e,d,f,h){var i;i=k||("Windows"==d&&"5.1"==f?g:k)||("Windows"==d&&"5.2"==f?g:k)||("Windows"==d&&"6.0"==f?g:k)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):k}(a,c,b,e,d,f,h);return!i?k:function(a,b,c,e){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(e))?(a=parseFloat(a[1]),525.13<=a&&534.5>a):k}(a,c,b,e,d,f,h)}));
X.addBrowser(new P("chrome4to5-linux-osx-win2003-win7plus-winvista-winxp","a",function(a,c,b,e,d,f,h){var i;i=(i=k||("Windows"==d&&"5.1"==f?g:k)||("Windows"==d&&"5.2"==f?g:k)||("Windows"==d&&"6.0"==f?g:k)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):k}(a,c,b,e,d,f,h))||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==
d&&"Unknown"==f?g:k}(a,c,b,e,d,f,h);return!i&&!("Ubuntu"==d||"Linux"==d?g:k)?k:function(a,b){if("Chrome"==a){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c){var d=parseFloat(c[1]),e=parseInt(c[2],10),c=parseInt(c[3],10);if(!(6<=d)&&(4<d||4==d&&249<e||4==d&&249==e&&4<=c))return g}}return k}(a,c,b,e,d,f,h)}));
X.addBrowser(new P("safariany-android2to3-ipad4-iphone4","a",function(a,c,b,e,d,f,h){var i;i=(i=(i=k||function(a,b,c,d,e,f){a=/([0-9]+).([0-9]+)/.exec(f);return"Android"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),2==e&&2<=a||3==e&&1>a):k}(a,c,b,e,d,f,h))||function(a,b,c,d,e,f){return"iPad"==e&&(a=/^([0-9]+)_([0-9]+)/.exec(f))?(b=parseInt(a[2],10),4==parseInt(a[1],10)&&2<=b):k}(a,c,b,e,d,f,h))||function(a,b,c,d,e,f){if("iPhone"==e||"iPod"==e)if(a=/^([0-9]+)_([0-9]+)/.exec(f))return b=parseInt(a[2],
10),4==parseInt(a[1],10)&&2<=b;return k}(a,c,b,e,d,f,h);return!i?k:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==d||"iPad"==d)?g:k}));
X.addBrowser(new P("safari5plus-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,e,d,f,h){var i;i=(i=k||("Windows"==d&&"5.1"==f?g:k)||("Windows"==d&&"5.2"==f?g:k)||("Windows"==d&&"6.0"==f?g:k)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):k}(a,c,b,e,d,f,h))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==
e&&"Unknown"==f?g:k}(a,c,b,e,d,f,h);return!i?k:function(a,b,c,e){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(e))?534.5<=parseFloat(a[1]):k}(a,c,b,e,d,f,h)}));
X.addBrowser(new P("opera10-linux-win2003-win7plus-winvista-winxp","a",function(a,c,b,e,d,f,h){var i;i=k||("Windows"==d&&"5.1"==f?g:k)||("Windows"==d&&"5.2"==f?g:k)||("Windows"==d&&"6.0"==f?g:k)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):k}(a,c,b,e,d,f,h);return!i&&!("Ubuntu"==d||"Linux"==d?g:k)?k:function(a,b){if("Opera"==a){var c=parseFloat(b);return 10.54<=c&&11.1>c}return k}(a,c,b,e,d,f,h)}));
X.addBrowser(new P("opera11plus-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,e,d,f,h){var i;i=(i=k||("Windows"==d&&"5.1"==f?g:k)||("Windows"==d&&"5.2"==f?g:k)||("Windows"==d&&"6.0"==f?g:k)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):k}(a,c,b,e,d,f,h))||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):
"Macintosh"==d&&"Unknown"==f?g:k}(a,c,b,e,d,f,h);return!i&&!("Ubuntu"==d||"Linux"==d?g:k)?k:"Opera"==a?11.1<=parseFloat(c):k}));
X.addBrowser(new P("safariany-ipad5plus-iphone5plus","d",function(a,c,b,e,d,f,h){var i;i=(i=k||function(a,b,c,d,e,f){return"iPad"==e?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):k:k}(a,c,b,e,d,f,h))||function(a,b,c,d,e,f){return"iPhone"==e||"iPod"==e?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):k:k}(a,c,b,e,d,f,h);return!i?k:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==d||"iPad"==d)?g:k}));
X.addBrowser(new P("chrome6plus-android3plus-chromeos-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,e,d,f,h){var i;i=(i=(i=k||("Windows"==d&&"5.1"==f?g:k)||("Windows"==d&&"5.2"==f?g:k)||("Windows"==d&&"6.0"==f?g:k)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):k}(a,c,b,e,d,f,h))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],
10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?g:k}(a,c,b,e,d,f,h))||("Ubuntu"==d||"Linux"==d?g:k)||function(a,b,c,e,d,f){a=/([0-9]+).([0-9]+)/.exec(f);return"Android"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),3==d&&1<=a||3<d):k}(a,c,b,e,d,f,h);return!(i||"CrOS"==d)?k:function(a,b){if("Chrome"==a){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c&&6<=parseFloat(c[1]))return g}}(a,c,b,e,d,f,h)}));
X.addBrowser(new P("air-osx","b",function(a,c,b,e,d,f,h){var i;i=k||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?g:k}(a,c,b,e,d,f,h);return!i?k:function(a,b){if("AdobeAIR"==a){var c=/([0-9]+.[0-9]+)/.exec(b);if(c)return 2.5<=parseFloat(c[1])}return k}(a,c,b,e,d,f,h)}));
X.addBrowser(new P("ff35-osx","b",function(a,c,b,e,d,f,h){var i;i=k||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?g:k}(a,c,b,e,d,f,h);return!i?k:function(a,b,c,d){return"Gecko"==c?(a=/1.9.1b[1-3]{1}/,/1.9.1/.test(d)&&!a.test(d)):k}(a,c,b,e,d,f,h)}));
X.addBrowser(new P("ff35-linux-win2003-win7plus-winvista-winxp","a",function(a,c,b,e,d,f,h){var i;i=k||("Windows"==d&&"5.1"==f?g:k)||("Windows"==d&&"5.2"==f?g:k)||("Windows"==d&&"6.0"==f?g:k)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):k}(a,c,b,e,d,f,h);return!i&&!("Ubuntu"==d||"Linux"==d?g:k)?k:function(a,b,c,d){return"Gecko"==c?(a=/1.9.1b[1-3]{1}/,/1.9.1/.test(d)&&!a.test(d)):k}(a,c,b,e,d,f,h)}));
var U=new function(){this.N=[];this.r={}};wa(new T("AllFonts",function(a,c){return c}));
wa(new T("DefaultFourFontsWithSingleFvdFamilies",function(a,c,b){for(var e=0;e<c.length;e++){var d=c[e],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+d;b.push(new ma(f,[d]))}a={};for(d=0;d<c.length;d++)b=c[d],e=b.charAt(1),(a[e]||(a[e]=[])).push(b);b=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];e=[];for(d=0;d<b.length;d++)for(var f=b[d],h=0;h<f.length;h++){var i=f[h];if(a[i]){e=e.concat(a[i]);break}}b=e;e={};a=[];for(d=0;d<b.length;d++)f=b[d],e[f]||(e[f]=g,a.push(f));b=[];for(e=0;e<c.length;e++){d=c[e];
for(f=0;f<a.length;f++)h=a[f],h==d&&b.push(h)}return b}));U.r.a="AllFonts";U.r.b="AllFonts";U.r.d="AllFonts";U.r.e="AllFonts";U.r.f="AllFonts";U.r.g="AllFonts";U.r.h="AllFonts";U.r.i="DefaultFourFontsWithSingleFvdFamilies";window.Typekit||(window.Typekit={});
if(!window.Typekit.load){var Aa=new O(g,"use.typekit.com","/"),Ba=(new s(navigator.userAgent,document)).parse(),Ca=new M(document,Ba),Da=function(a,c){setTimeout(a,c)},Y=new R(Aa,Ca,Ba,document.documentElement,Da),Z=new S(window,Ca,Da);window.Typekit.load=function(){Y.load.apply(Y,arguments)};window.Typekit.addKit=function(){Y.H.apply(Y,arguments)}}var Ea,Fa,$;Ea=new O(g,"use.typekit.com","/k");Fa=new function(){this.S=this.U=j};$=new oa("fww1mvh");$.setSecurityToken("3bb2a6e53c9684ffdc9a98f01b5b2a62e205eae2cde7d9d1445a914d5137800c614ec9db6b0e1513a7e343706b39043c4f98af351c9f6f383d730f3affcc76a58d417bf4a68e6d9d646ae2f0652adca5f58806700a62102080c4cb360bfce43229a29031c9f4b7bf18eda77b197f6e7c8b79d1a8b9c3be0505296b6b4d91d643d0913bb1b44fdd76e1c15bf19f53997b54d081942ae9e9b9a092d233b8d9012fa217b7983b00d0fa623be32141cf17b0e61d9fa7595d64f1c0e17158a9b90cb3aaddf19b6f0d1a2a7fa9111d931fec7c46be3b002d8dae8dcaf5bcb7b4e96149984741bfc0b9a688c9b9c06bae0cdcf6998db58a404dd632a83613888d10b2f251962126fe");
$.setNestedUrl(Ea);$.setKitOptions(Fa);$.addFontFamily(new N("freight-sans-pro",["n7"]));$.addFontFamily(new N("proxima-nova",["n4","n6","n7"]));$.addCssRule(new ia([".tk-freight-sans-pro"],[{value:'"freight-sans-pro",sans-serif',name:"font-family"}]));$.addCssRule(new ia([".tk-proxima-nova"],[{value:'"proxima-nova",sans-serif',name:"font-family"}]));$.addBrowser(X.getBrowserById("air-linux-win"));$.addBrowser(X.getBrowserById("air-osx"));$.addBrowser(X.getBrowserById("chrome4to5-linux-osx-win2003-win7plus-winvista-winxp"));
$.addBrowser(X.getBrowserById("chrome6plus-android3plus-chromeos-linux-osx-win2003-win7plus-winvista-winxp"));$.addBrowser(X.getBrowserById("ff35-linux-win2003-win7plus-winvista-winxp"));$.addBrowser(X.getBrowserById("ff35-osx"));$.addBrowser(X.getBrowserById("ff36plus-linux-osx-win2003-win7plus-winvista-winxp"));$.addBrowser(X.getBrowserById("ie6to8-win2003-win7plus-winvista-winxp"));$.addBrowser(X.getBrowserById("ie9plus-win7plus-winvista"));$.addBrowser(X.getBrowserById("opera10-linux-win2003-win7plus-winvista-winxp"));
$.addBrowser(X.getBrowserById("opera10-osx"));$.addBrowser(X.getBrowserById("opera11plus-linux-osx-win2003-win7plus-winvista-winxp"));$.addBrowser(X.getBrowserById("safari3to5-osx"));$.addBrowser(X.getBrowserById("safari3to5-win2003-win7plus-winvista-winxp"));$.addBrowser(X.getBrowserById("safari5plus-osx-win2003-win7plus-winvista-winxp"));$.addBrowser(X.getBrowserById("safariany-android2to3-ipad4-iphone4"));$.addBrowser(X.getBrowserById("safariany-android3plus"));$.addBrowser(X.getBrowserById("safariany-ipad5plus-iphone5plus"));
$.setFontFilterSet(U);Z&&Z.ca.__webfonttypekitmodule__?(Z.H($),Z.load()):window.Typekit.addKit($);
})(this,document);
window.Typekit.config={"p":"//p.typekit.net/p.gif?s=1&k=fww1mvh&ht=tk&h={host}&f=13454.139.175.173&a=6834&_={_}"};
/*{"k":"1.1.0","created":"2012-08-20T20:46:40Z"}*/
;(function(window,document,undefined){
function e(a){this.a=a}e.prototype=function(a){this.a=a}.prototype;function f(a){var b=new Image(1,1);b.src=a;b.onload=function(){b.onload=null}}function g(){this.c=window.Typekit.config.p}function h(a,b,c){var d=c||{},a=a.c.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,c){return c&&d[b]?"/"+d[b].join("/"):d[b]||""});a.match(/^\/\//)&&(a=(b?"https:":"http:")+a);return a.replace(/\/*\?*($|\?)/,"$1")}window.Typekit||(window.Typekit={});var i=new e(document),j=new function(){this.b=new g},k=!1;
function l(){if(!k)for(var a=document.getElementsByTagName("link"),b=0;b<a.length;b++){var c=a[b].getAttribute("href");if(c&&0<=c.indexOf("use.typekit")){a=j;b=i;a.b&&(c=(c=window.__adobewebfontsappname__)?c.toString().substr(0,20):"",f(h(a.b,"https:"==b.a.location.protocol,{host:encodeURIComponent(b.a.location.hostname),app:encodeURIComponent(c),_:(+new Date).toString()})));k=!0;break}}}var m=window.Typekit.load;window.Typekit.load=function(){m&&m.apply(window.Typekit,arguments);l()};
window.__webfonttypekitmodule__&&l();
})(this,document);
