<?php

/*

  type: layout

  name: Default

  description: default


*/
?>
<div>
    <style>
        .toc-<?php echo $params['id'];?> {
        }
        .toc-<?php echo $params['id'];?> ul {
        }
        .toc-<?php echo $params['id'];?> ul li a {
        }
        .toc-<?php echo $params['id'];?> li ul {
        }
        /* active class is generated by the scrollspy */
        .toc-<?php echo $params['id'];?> li.active > a {
        }
        .toc-<?php echo $params['id'];?> li.active > ul {
        }
    </style>

    <nav id="toc-<?php echo $params['id'];?>"></nav>

</div>
