<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * AI-58 / TICKET-RR (cycle-65 2026-05-08): newsletter tracked-link
 * allowlist table.
 *
 * The cycle-64 HMAC layer guarantees that a click-link URL was
 * generated by our sender — but it does not constrain WHERE a campaign
 * can link. An admin (or anyone with campaign-edit access) could still
 * configure a campaign to redirect subscribers to a malicious external
 * host. This table stores the explicit list of host patterns that
 * tracked-link redirects are allowed to target. Cross-host clicks
 * outside the allowlist fall through to the cycle-7 same-host
 * fallback (= redirect to home, no record).
 *
 * Schema decisions:
 *   - `host_pattern` (string, indexed): the canonical host or wildcard
 *     pattern, e.g. `example.com` or `*.example.com`. We deliberately
 *     do NOT validate scheme — the route already restricts to http/https.
 *   - `note` (string nullable): human-readable reason, e.g. "Marketing
 *     landing pages". Surfaced in the Filament admin UI.
 *   - `is_active` (bool): allows soft-disable without deletion so the
 *     audit trail is preserved.
 *   - `created_by` / `updated_by`: optional FK back to users for
 *     accountability.
 *   - timestamps: standard Laravel.
 *
 * The site's own host is implicitly allowed (cycle-7 same-host fallback)
 * — operators don't need to add their own host to the allowlist.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (Schema::hasTable('newsletter_tracked_link_allowlist')) {
            return;
        }

        Schema::create('newsletter_tracked_link_allowlist', function (Blueprint $table) {
            $table->id();
            $table->string('host_pattern')->index();
            $table->string('note')->nullable();
            $table->boolean('is_active')->default(true)->index();
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->timestamps();

            // No FK constraint on user ids — Microweber's user table
            // location varies between deployments and we want this
            // migration to apply cleanly regardless.
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('newsletter_tracked_link_allowlist');
    }
};
