<?php
use Omnipay\Omnipay;

$stripe_is_checkout = (get_option('stripe_checkout', 'payments')) == 'y';

// Include the Stripe library - mainly for setting and storing api keys and logging results
$parent_dir = dirname(dirname(__FILE__)).DS;
include_once ($parent_dir.'lib/Stripe.php');

// Create an instance of local Stripe library - this will switch api keys between live and test depending on MW option stripe_testmode option value
$mwStripe = new Stripe();

if($stripe_is_checkout=='y') {

	if (!$mwStripe->checkApiKeys(true)) {
		$place_order['error'] = 'Stripe Api key is not set.';
		return;
	}

	// save in-page payment form in session parameter payment_form then redirect to template payment page to output payment form

	$mwStripe->prepareCheckout($mw_return_url,$place_order);

	// set checkout parameters including redirect to payment template to load checkout overlay
	$place_order['order_completed'] = 1;
	$place_order['is_paid'] = 0;
	$place_order['success'] = $mwStripe->getRedirectForm();

} else {

    $gateway = Omnipay::create('Stripe');

	$formData = include(dirname(__DIR__).DS.'lib'.DS.'omnipay'.DS.'omnipay_populate_form_data.php');


	try {
		// Send purchase request
		$response = $gateway->purchase(
			array(
				'amount'   => $place_order['amount'],
				'currency' => $place_order['currency'],
				'card'     => $formData
			)
		)->send();

		if ($response->isSuccessful()){
			$place_order['transaction_id'] = $response->getTransactionReference(); // a reference generated by the payment gateway
			$place_order['success'] = 'Your payment was successful! ' . $response->getMessage();
			$place_order['is_paid'] = 1;
			$place_order['order_completed'] = 1;

		} elseif ($response->isRedirect()) {
			$place_order['error'] = 'Stripe redirect is not supported yet';
		   // return $response->redirect();

		} else {
			$place_order['error'] = $response->getMessage();

		}
	} catch (\Omnipay\Common\Exception\InvalidCreditCardException $e) {
		$msg = $e->getMessage();

		$place_order['error'] = $msg;

	} catch (\Exception $e) {
		$msg = $e->getMessage();
		$place_order['error'] = $msg;
	}

}