<?php
use Omnipay\Omnipay;

$api_key = get_option('payzum_api_key', 'payments');
$webhook_secret = get_option('payzum_webhook_secret', 'payments');
$test_mode = get_option('payzum_test_mode', 'payments') == 'y';

include __DIR__.'/../lib/legacy_fields.php';

$gateway = Omnipay::create('Payzum');
$gateway->setApiKey($api_key);
$gateway->setWebhookSecret($webhook_secret);
$gateway->setTestMode($test_mode);

$formData = include(dirname(__DIR__).DS.'lib'.DS.'omnipay'.DS.'omnipay_populate_form_data.php');
try {
    // Send purchase request. Payzum creates a hosted-checkout invoice, so the
    // response is always a redirect; the order settles later through notify.php
    // when the signed payment notification arrives.
    $response = $gateway->purchase(
        array(
            'amount'   => $place_order['amount'],
            'currency' => $place_order['currency'],
            'description' => $place_order['item_name'],
            'transactionId' => $place_order['payment_verify_token'],

            'returnUrl' => $mw_return_url,
            'notifyUrl' => $mw_ipn_url,
            'cancelUrl' => $mw_cancel_url,
        )
    )->send();

    if ($response->isRedirect()) {
        $place_order['transaction_id'] = $response->getTransactionReference(); // a reference generated by the payment gateway
        $place_order['order_completed'] = 1;
        $place_order['is_paid'] = 0;
        $place_order['redirect'] = $response->getRedirectUrl();
    } else {
        $place_order['error'] = $response->getMessage();
    }
} catch (\Exception $e) {
    $msg = $e->getMessage();
    $place_order['error'] = $msg;
}
